function decode() {}
function encode() {}
function readHeader() {}
function writeHeader() {}
function readBit() {}
function flushBuffer() {}
function writeBit() {}
function decodeBitStream() {}
function encodeAlphabet() {}
function buildTree() {}
function addLeaves() {}
function addNode() {}
function determineFrequency() {}
